// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rbsjcjtnddjforkvckbn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJic2pjanRuZGRqZm9ya3Zja2JuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ4ODg0MTgsImV4cCI6MjA2MDQ2NDQxOH0.ft90JxZtNmeme_HI6NSWJs5lKyO4B-REA2Xn3UIfFiY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);